sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dk170589/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dk170589/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-347970119720"
  bucket_path: "docker-react"
  on:
   branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: $AWS_SECRET_KEY
   secure: $AWS_SECRET_KEY